#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

fail() { echo "FAIL: $1" >&2; exit 1; }
pass() { echo "PASS: $1"; }

require_file() {
  [[ -f "$1" ]] || fail "missing file: $1"
}

require_grep() {
  grep -q "$2" "$1" || fail "expected pattern in $1: $2"
}

require_file "scripts/install.sh"
require_file "scripts/_pilear-common.sh"
[[ -x "scripts/install.sh" ]] || fail "scripts/install.sh must be executable"

require_file "package.json"
require_file "HARNESS.md"
require_file "extensions/learning-root.ts"
require_file "extensions/_pilear-utils.ts"
require_file "extensions/graph-index-core.ts"
require_file "extensions/graph-index.ts"
python3 -c "import json; d=json.load(open('package.json')); assert 'pi' in d" \
  || fail "package.json missing pi manifest"

require_file "prompts/teach.md"
require_file "prompts/review.md"
require_file "prompts/design.md"
require_file "prompts/explore.md"
require_file "prompts/recall.md"
require_file "prompts/blog.md"
require_file "prompts/next.md"
require_file "prompts/map.md"
require_file "prompts/suggest-links.md"
require_file "skills/deep-dive/SKILL.md"
require_file "skills/design-review/SKILL.md"
require_file "skills/mock-design/SKILL.md"
require_file "skills/code-explore/SKILL.md"
require_file "skills/recall/SKILL.md"
require_file "skills/blog/SKILL.md"
require_file "skills/discover/SKILL.md"
require_file "skills/link-suggest/SKILL.md"
require_file "extensions/overview-connections.ts"
require_file "skills/_shared/flows.md"
require_file "skills/_shared/blog-voice.md"
require_file "skills/_shared/voice-patterns.md"
require_file "skills/_shared/voice-examples.md"
require_file "skills/_shared/voice-exclusions.md"
require_file "skills/_shared/blog-pipeline.md"
require_file "skills/_shared/mission-format.md"
require_file "skills/_shared/learning-record-format.md"
require_file "skills/_shared/resources-format.md"
require_file "skills/_shared/glossary-format.md"
require_file "skills/_shared/notes-format.md"

for skill in deep-dive design-review mock-design code-explore recall; do
  f="skills/${skill}/SKILL.md"
  require_grep "$f" "^name: ${skill}$"
  require_grep "$f" "^description:"
  require_grep "$f" "_shared/flows.md"
done

require_grep "skills/_shared/flows.md" "Research (required before teaching)"
require_grep "skills/_shared/flows.md" "Feynman gate"
require_grep "skills/deep-dive/SKILL.md" "research.md"
require_grep "HARNESS.md" "research.md"
require_grep "skills/_shared/flows.md" "Deliberate-practice feedback"
require_grep "skills/_shared/flows.md" "Learning record"
require_grep "skills/_shared/mission-format.md" "MISSION.md"
require_grep "skills/_shared/learning-record-format.md" "learning-records"

require_grep "HARNESS.md" "<learning-root>/<domain>/<subject>/"
require_grep "HARNESS.md" "MISSION.md"
require_grep "HARNESS.md" "learning-records"
require_grep "HARNESS.md" "glossary.md"
require_grep "HARNESS.md" "resources.md"
require_grep "HARNESS.md" "NOTES.md"
require_grep "HARNESS.md" "Feynman"
require_grep "HARNESS.md" "recall"
require_grep "HARNESS.md" "Source quality"
require_grep "HARNESS.md" "Pasted material"
require_grep "HARNESS.md" "Spaced recall"
require_grep "skills/deep-dive/SKILL.md" "Feynman gate"
require_grep "skills/deep-dive/SKILL.md" "MISSION.md"
require_grep "skills/deep-dive/SKILL.md" "learning-records"
require_grep "skills/deep-dive/SKILL.md" "glossary.md"
require_grep "skills/deep-dive/SKILL.md" "resources.md"
require_grep "skills/recall/SKILL.md" "Retrieval"
require_grep "skills/recall/SKILL.md" "learning-records"
require_grep "skills/discover/SKILL.md" "MISSION.md"
require_grep "prompts/teach.md" "deep-dive"
require_grep "prompts/review.md" "design-review"
require_grep "prompts/design.md" "mock-design"
require_grep "prompts/explore.md" "code-explore"
require_grep "prompts/recall.md" "recall"
require_grep "prompts/blog.md" "blog"
require_grep "skills/blog/SKILL.md" "^name: blog$"
require_grep "skills/blog/SKILL.md" "blog-voice.md"
require_grep "skills/blog/SKILL.md" "voice-patterns.md"
require_grep "skills/blog/SKILL.md" "voice-examples.md"
require_grep "skills/blog/SKILL.md" "voice-exclusions.md"
require_grep "skills/blog/SKILL.md" "blog-pipeline.md"
require_grep "skills/blog/SKILL.md" "first-draft-blog.md"
require_grep "skills/blog/SKILL.md" "blog/diagrams"
require_grep "skills/blog/SKILL.md" "skip-diagrams"
require_grep "skills/blog/SKILL.md" "blog/wisdom.md"
require_grep "skills/blog/SKILL.md" "check_falsifiability"
require_grep "skills/blog/SKILL.md" "falsifiability-audit.md"
require_grep "skills/blog/SKILL.md" "fact-audit.md"
require_grep "skills/blog/SKILL.md" "concept-gate.md"
require_grep "skills/blog/SKILL.md" "skip-correctness"
require_grep "skills/blog/SKILL.md" "mental-model-audit.md"
require_grep "skills/blog/SKILL.md" "skip-mental-model"
require_grep "skills/_shared/blog-pipeline.md" "Mental picture"
require_grep "skills/_shared/blog-voice.md" "Conciseness"
require_grep "skills/_shared/blog-pipeline.md" "Tighten"
require_grep "HARNESS.md" "blog"
require_grep "scripts/install.sh" "pi update"
require_grep "scripts/install.sh" "pi install -l"
require_grep "scripts/_pilear-common.sh" "merge_settings"
require_grep "extensions/_pilear-utils.ts" "PILEAR_ROOT"
require_grep "extensions/learning-root.ts" "resolveLearningRoot"
require_grep "package.json" "graph-index.ts"
require_grep "skills/discover/SKILL.md" "^name: discover$"
require_grep "skills/link-suggest/SKILL.md" "^name: link-suggest$"
require_grep "HARNESS.md" "discover"
require_grep "HARNESS.md" "link-suggest"
require_grep "prompts/next.md" "discover"

bash scripts/test-graph-index.sh

pass "harness structure"
